language: c

sudo: true

notifications:
  email: false

before_install:
  - wget https://github.com/devkitPro/pacman/releases/download/devkitpro-pacman-1.0.1/devkitpro-pacman.deb
  - sudo dpkg -i devkitpro-pacman.deb

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - libstdc++-4.9-dev

install:
  - sudo dkp-pacman -Syu 3ds-dev --noconfirm --needed
  - sudo dkp-pacman -Syu 3ds-mpg123 --noconfirm
  - sudo dkp-pacman -Syu 3ds-libvorbisidec --noconfirm
  - sudo dkp-pacman -Syu 3ds-opusfile --noconfirm
  - sudo dkp-pacman -Syu 3ds-jansson --noconfirm
  - sudo dkp-pacman -Syu 3ds-wildmidi --noconfirm
  - source /etc/profile.d/devkit-env.sh
  - git clone --recursive https://github.com/Steveice10/bannertool && cd bannertool/
  - make && sudo cp output/linux-x86_64/bannertool /opt/devkitpro/devkitARM/bin/bannertool
  - cd ../ && rm -rf bannertool/
  - git clone https://github.com/profi200/Project_CTR.git && cd Project_CTR/makerom
  - make && sudo cp makerom /opt/devkitpro/devkitARM/bin/makerom
  - cd ../.. && rm -rf Project_CTR

script:
  - cd $TRAVIS_BUILD_DIR
  - make clean && make
